version: '2'

services:

  chronograf:
    image: chronograf:1.8.8-alpine
    ports:
      - "8888:8888"

  influxdb:
    image: influxdb:1.8.3
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - ./data_influxdb:/var/lib/influx:rw

  kapacitor:
    image: kapacitor:1.5.7
    ports:
      - "9092:9092"
    volumes:
      - ./data_kapacitor:/var/lib/kapacitor:rw
      - ./kapacitor.conf:/etc/kapacitor/kapacitor.conf
      
  telegraf:
    image: telegraf:1.16.3
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    links:
      - influxdb:influxdb

volumes:
  data_influxdb:
  data_kapacitor:
  kapacitor.conf:
  telegraf.conf:
    